spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parcial
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level.org.springframework.web: DEBUG